### ISSUE TITLE
边栏的链接挂了

### ISSUE THREAD

**Issue by 2926295173** [Enoch2090/MAGI#1]

**Comment by Enoch2090** [comment]
确实，因为现在的版本部署起来需要配置 Metarank 和 elasticsearch 服务以实现混合搜索，这两者需要额外的服务器。这个项目刚开始做的时候 GPT 这些东西还没有火起来，所以很多轮子我自己造掉了。我计划之后有空用 Langchain 重写一部分代码，让这个项目支持 OpenAI 的 API 也能作为 embedding encoder。感谢您的关注！
